name: StartupCommands
version: 0.0.7
api-version: 1.16
main: me.mattgd.startupcommands.StartupCommands
author: mattgd
description: A Minecraft server plugin that automatically runs commands on startup.

commands:
   startup:
      description: Manage the StartupCommands plugin settings.
      usage: /<command> [args]
      permission: startupcommands.manage
      aliases: [startupcommands, startupcommand, startupcmd, sc]
permissions:
   startupcommands.manage:
      description: Allows you to manage the StartupCommands plugin settings
      default: op